/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-Sik_Radios
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_SIK_RADIOS_API_H
#define INCLUDED_SIK_RADIOS_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_Sik_Radios_EXPORTS
#define SIK_RADIOS_API __GR_ATTR_EXPORT
#else
#define SIK_RADIOS_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_SIK_RADIOS_API_H */
